'use client'

import './globals.css'
import { CurrentUserContext } from '@/user'
import React, { useState, useContext } from 'react'
import Navbar from '@/components/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const context = useContext(CurrentUserContext)
  const [darkTheme, setDarkTheme] = useState<boolean>(true)
  const [currentUser, setCurrentUser] = useState<any>(null)
  const [items, setItems] = useState({
    currentUser,
    setCurrentUser
  })
  const data = {
    append: (args: object) => {
      setItems({
        ...items,
        ...args
      })
    },
    ...items
  }
  return (
    <html
      lang='en'
      className={`w-full h-full`}
      data-theme={darkTheme ? 'dark' : 'light'}
    >
      <CurrentUserContext.Provider value={data}>
        <body
          className={`w-full h-full dark:bg-black dark:text-white bg-white text-black`}
        >
          <Navbar
            darkThemeProvider={darkTheme}
            setter={() => setDarkTheme(prev => !prev)}
          />
          <div className='flex mt-20'>
            <div
              id='first'
              className='w-20'
            ></div>
            <div
              id='second'
              className='grow'
            >
              {children}
            </div>
            <div
              id='third'
              className='w-20'
            ></div>
          </div>
        </body>
      </CurrentUserContext.Provider>
    </html>
  )
}
