'use client'

import './globals.css'
import { MoonIcon, SunIcon } from '@heroicons/react/24/outline'
import React, { useState } from 'react'
import { QueryClientProvider, QueryClient } from '@tanstack/react-query'
import { SessionProvider, useSession } from 'next-auth/react'
import Image from 'next/image'
import Link from 'next/link'
import Navbar from '@/components/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const queryClient = new QueryClient()

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const [darkTheme, setDarkTheme] = useState<boolean>(true)
  return (
    <html
      lang='en'
      className={`w-full h-full`}
      data-theme={darkTheme ? 'dark' : 'light'}
    >
      <SessionProvider>
        <QueryClientProvider client={queryClient}>
          <body
            className={`w-full h-full dark:bg-black dark:text-white bg-white text-black`}
          >
            <Navbar darkThemeProvider={darkTheme} setter={() => setDarkTheme(prev => !prev)} />
            <div className='flex mt-20'>
              <div
                id='first'
                className='w-20'
              ></div>
              <div
                id='second'
                className='grow'
              >
                {children}
              </div>
              <div
                id='third'
                className='w-20'
              ></div>
            </div>
          </body>
        </QueryClientProvider>
      </SessionProvider>
    </html>
  )
}
